// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjqjqzvhobujmxywjnlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcWpxenZob2J1am14eXdqbmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzM1MzMsImV4cCI6MjA2NTE0OTUzM30.4Zmr-WcWmjoDsZLny_frwDxdwK2d01YdELKLvzvp4Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);